#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "  Chained remove"
    echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...]"
    echo "      For each ITEM#, calls command rm."
    echo ""
    exit
}

for i in $(seq 1 $#); do
    $TODO_FULL_SH -f command rm ${!i};
done
